version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_BOT_TOKEN=5487638486:AAH8GBoz-BLzMLkdZMMBZZYc7rEQSIzbfxQ
      - TELEGRAM_CHAT_ID=185857885

    restart: unless-stopped
    volumes:
      - ./src/data:/app/src/data